<?php
return [
    // Neck & Traps
    'Neck Curl' => 'Neck',
    'Neck Extension' => 'Neck',
    'Neck Lateral Flexion' => 'Neck',
    'Barbell Shrugs' => 'Traps',
    'Dumbbell Shrugs' => 'Traps',
    'Farmer Carry' => 'Traps',
    'Upright Row' => 'Traps',
    'Face Pull' => 'Traps',

    // Shoulders
    'Overhead Press (Barbell)' => 'Shoulders',
    'Overhead Press (Dumbbell)' => 'Shoulders',
    'Overhead Press (Machine)' => 'Shoulders',
    'Arnold Press' => 'Shoulders',
    'Lateral Raise (Dumbbell)' => 'Shoulders',
    'Lateral Raise (Cable)' => 'Shoulders',
    'Lateral Raise (Machine)' => 'Shoulders',
    'Front Raise (Dumbbell)' => 'Shoulders',
    'Front Raise (Plate)' => 'Shoulders',
    'Rear Delt Fly (Dumbbell)' => 'Shoulders',
    'Rear Delt Fly (Cable)' => 'Shoulders',
    'Rear Delt Fly (Machine)' => 'Shoulders',
    'Face Pull' => 'Shoulders',
    'Upright Row (Barbell)' => 'Shoulders',
    'Upright Row (Cable)' => 'Shoulders',
    'Landmine Press' => 'Shoulders',

    // Chest
    'Push-ups' => 'Chest',
    'Incline Push-ups' => 'Chest',
    'Decline Push-ups' => 'Chest',
    'Diamond Push-ups' => 'Chest',
    'Bench Press' => 'Chest',
    'Incline Bench Press' => 'Chest',
    'Decline Bench Press' => 'Chest',
    'Dumbbell Press' => 'Chest',
    'Incline Dumbbell Press' => 'Chest',
    'Decline Dumbbell Press' => 'Chest',
    'Chest Fly (Dumbbells)' => 'Chest',
    'Floor Dumbbell Fly' => 'Chest',
    'Cable Crossover' => 'Chest',
    'Cable Low to High Crossover' => 'Chest',
    'Pec Deck Machine' => 'Chest',
    'Dumbbell Pullover' => 'Chest',
    'Close-Grip Bench Press' => 'Chest',
    'Medicine Ball Push-ups' => 'Chest',
    'Floor Press' => 'Chest',
    'Isometric Chest Squeeze' => 'Chest',
    'Isometric Chest Squeeze with Ball' => 'Chest',
    'Plyometric Push-ups' => 'Chest',
    'Medicine Ball Chest Pass' => 'Chest',
    'Single-arm Dumbbell Press on Stability Ball' => 'Chest',
    'Chest Dips' => 'Chest',
    'Standing Cable Chest Press' => 'Chest',
    'Resistance Band Chest Fly' => 'Chest',

    // Back
    'Pull-up' => 'Back',
    'Chin-up' => 'Back',
    'Lat Pulldown (Wide Grip)' => 'Back',
    'Lat Pulldown (Close Grip)' => 'Back',
    'Lat Pulldown (Reverse Grip)' => 'Back',
    'Barbell Row (Standard)' => 'Back',
    'Barbell Row (Pendlay)' => 'Back',
    'Dumbbell Row (Single Arm)' => 'Back',
    'Dumbbell Row (Incline Bench)' => 'Back',
    'T-Bar Row (Barbell)' => 'Back',
    'T-Bar Row (Machine)' => 'Back',
    'Seated Cable Row (V-Bar)' => 'Back',
    'Seated Cable Row (Straight Bar)' => 'Back',
    'Seated Cable Row (Wide Grip)' => 'Back',
    'Deadlift (Conventional)' => 'Back',
    'Deadlift (Sumo)' => 'Back',
    'Romanian Deadlift' => 'Hamstrings',
    'Trap Bar Deadlift' => 'Back',
    'Inverted Row' => 'Back',
    'Machine Back Extension' => 'Back',

    // Biceps
    'Barbell Curl (Standard)' => 'Biceps',
    'Barbell Curl (EZ Bar)' => 'Biceps',
    'Dumbbell Curl (Standing)' => 'Biceps',
    'Dumbbell Curl (Seated)' => 'Biceps',
    'Hammer Curl (Dumbbell)' => 'Biceps',
    'Hammer Curl (Cable)' => 'Biceps',
    'Preacher Curl (Barbell)' => 'Biceps',
    'Preacher Curl (Dumbbell)' => 'Biceps',
    'Preacher Curl (Machine)' => 'Biceps',
    'Concentration Curl' => 'Biceps',
    'Spider Curl' => 'Biceps',
    'Cable Curl' => 'Biceps',
    'Incline Dumbbell Curl' => 'Biceps',

    // Triceps
    'Skull Crushers (Barbell)' => 'Triceps',
    'Skull Crushers (Dumbbell)' => 'Triceps',
    'Skull Crushers (EZ Bar)' => 'Triceps',
    'Tricep Pushdown (Cable Rope)' => 'Triceps',
    'Tricep Pushdown (Straight Bar)' => 'Triceps',
    'Overhead Tricep Extension (Dumbbell)' => 'Triceps',
    'Overhead Tricep Extension (Cable)' => 'Triceps',
    'Close-Grip Bench Press' => 'Triceps',
    'Bench Dips' => 'Triceps',
    'Kickbacks (Dumbbell)' => 'Triceps',
    'Kickbacks (Cable)' => 'Triceps',

    // Forearms
    'Wrist Curl' => 'Forearms',
    'Reverse Wrist Curl' => 'Forearms',
    'Farmer’s Walk' => 'Forearms',
    'Plate Pinch' => 'Forearms',
    'Towel Pull-up' => 'Forearms',
    'Dead Hang' => 'Forearms',
    'Rice Bucket Training' => 'Forearms',
    'Fingertip Push-up' => 'Forearms',
    'Wrist Roller' => 'Forearms',
    'Hammer Curl' => 'Forearms',
    'Reverse Curl' => 'Forearms',

    // Legs & Glutes
    'Back Squat' => 'Quads',
    'Front Squat' => 'Quads',
    'Goblet Squat' => 'Quads',
    'Smith Machine Squat' => 'Quads',
    'Bulgarian Split Squat' => 'Quads',
    'Lunge (Walking)' => 'Quads',
    'Lunge (Reverse)' => 'Quads',
    'Side Lunge' => 'Quads',
    'Curtsy Lunge' => 'Glutes',
    'Leg Press (Machine)' => 'Quads',
    'Leg Curl (Seated)' => 'Hamstrings',
    'Leg Curl (Lying)' => 'Hamstrings',
    'Leg Extension (Machine)' => 'Quads',
    'Hip Thrust (Barbell)' => 'Glutes',
    'Hip Thrust (Machine)' => 'Glutes',
    'Glute Bridge' => 'Glutes',
    'Step-Up' => 'Glutes',
    'Calf Raise (Standing)' => 'Calves',
    'Calf Raise (Seated)' => 'Calves',
    'Sled Push' => 'Legs',
    'Sled Pull' => 'Legs',
    'Sumo Deadlift' => 'Hamstrings',
    'Single Leg Deadlift' => 'Hamstrings',

    // Core / Abs
    'Crunch' => 'Abs',
    'Sit-Up' => 'Abs',
    'Plank' => 'Abs',
    'Side Plank' => 'Abs',
    'Hanging Leg Raise' => 'Abs',
    'Russian Twist' => 'Abs',
    'Ab Wheel Rollout' => 'Abs',
    'Bicycle Crunch' => 'Abs',
    'Mountain Climbers' => 'Abs',
    'V-Up' => 'Abs',
    'Flutter Kicks' => 'Abs',
    'Cable Woodchopper' => 'Abs',

    // Cardio / Functional / Full Body
    'Running' => 'Cardio',
    'Sprint' => 'Cardio',
    'Cycling' => 'Cardio',
    'Rowing' => 'Cardio',
    'Jump Rope' => 'Cardio',
    'Swimming' => 'Cardio',
    'Elliptical' => 'Cardio',
    'Stair Climber' => 'Cardio',
    'Battle Ropes' => 'Full Body',
    'Kettlebell Swing' => 'Full Body',
    'Clean and Press' => 'Full Body',
    'Snatch' => 'Full Body',
    'Turkish Get-Up' => 'Full Body',
    'Burpees' => 'Full Body',
    'Medicine Ball Slam' => 'Full Body',
    'Thrusters' => 'Full Body',
    'Push Press' => 'Full Body',
    'Man Makers' => 'Full Body',
];